### ISSUE TITLE
Замечания по lw3/task1

### ISSUE THREAD

**Issue by ivklgn** [seimurinspace/web-development-course#3]
```
  font-family: 'Work Sans', sans-serif;
```
нужно определить в body для все страницы один раз

**Comment by ivklgn** [comment]
```css
tbody {
  width: 100%;
}
``` 

не используется

**Comment by ivklgn** [comment]
```css
.sum-discount,
.sum-delivery,
.sum-subtotal,
.sum-total {
  display: flex;
  width: 300px;
  height: 100px;
  border: 5px solid rgba(0, 0, 0, .07);
  text-align: center;
  margin: 0 10px;
  justify-content: space-around;
  align-items: center;
  font-family: 'Work Sans',
    sans-serif;
}
```

лучше обобщить под одним классом.

**Comment by ivklgn** [comment]
```css
.checkout-basket img {
  width: 15px;
  left: 0;
  -webkit-filter: invert(1);
  filter: invert(1);
}
```

img - свой класс
